# Model settings
model:
  name: "microsoft/wavlm-large" # encoder backbone
  projection_dim: 1024
  prediction_dim: 2048
  ema_decay: 0.997

# Training settings
training:
  batch_size: 36
  num_workers: 8
  num_epochs: 100
  learning_rate: 1.0e-5
  weight_decay: 1.0e-5
  checkpoint_dir: "checkpoints/byol/wavlm_large-snr2_20-ema_997"
  log_dir: "outputs/byol/wavlm_large-snr2_20-ema_997"
  seed: 42
  early_stopping_metric: "val_loss"  # Options: "val_loss" or "val_avg_similarity"
  early_stopping_patience: 4
  early_stopping_min_delta: 0.005

# Data settings
data:
  clean_data_path: "/proj/speech/users/syk2145/data/Audios_en_sgmse/clean"
  noise_data_path: "/proj/speech/projects/noise_robustness/Audioset/Audioset-train"
  sample_rate: 16000
  max_audio_length: 5.0  # in seconds
  snr_range: [2, 5, 10, 15, 20]
  validation_ratio: 0.15  # 15% of data used for validation

# Logging settings
logging:
  wandb_mode: "offline" # "online", "offline", or "disabled"
  level: "INFO"      # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_level: "ERROR"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  metric_logging_interval: 4
  visualization_interval: 2

# Emotion recognition settings
emotion:
  encoder_checkpoint: "checkpoints/byol/wavlm_large-val_loss/wavlm_large-snr2_20-ema_997.pt"  # Path to pre-trained encoder
  checkpoint_dir: "checkpoints/emotion/wavlm_large-snr2" # path to save trained emotion model
  labels_file: "/proj/speech/users/syk2145/nrse/labels/processed/labels_consensus_processed.csv"
  train_dataset_split: "Development"
  validataion_dataset_split: "Test1"
  hidden_dim: 1024
  batch_size: 36
  learning_rate: 1.0e-4
  fine_tuning_lr: 5.0e-6  # Lower learning rate for fine-tuning
  scheduler_patience: 2  # Number of epochs with no improvement after which learning rate will be reduced
  weight_decay: 1.0e-4
  dropout_rate: 0.3
  classifier_epochs: 20  # Train classifier first
  fine_tuning_epochs: 10  # Then fine-tune with encoder
  patience: 3  # Early stopping patience
  unfreeze_encoder: false  # Whether to unfreeze encoder during training
  add_noise_during_training: true  # Whether to add noise during training
  use_class_weights: true  # Whether to use class weights for imbalanced data
  categorical_only: true
