# Model settings
model:
  name: "microsoft/wavlm-base-plus"
  projection_dim: 512
  prediction_dim: 768
  ema_decay: 0.996

# Training settings
training:
  batch_size: 64
  num_workers: 8
  num_epochs: 30
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  checkpoint_dir: "checkpoints/dev"
  log_dir: "outputs/dev"
  seed: 42
  early_stopping_metric: "val_avg_similarity"
  early_stopping_patience: 5

# Data settings
data:
  clean_data_path: "/proj/speech/users/syk2145/data/samples/Audios"
  noise_data_path: "/proj/speech/users/syk2145/data/samples/Audioset"
  sample_rate: 16000
  max_audio_length: 5.0  # in seconds
  snr_range: [-10, -5, 0, 5, 10, 15, 20]
  validation_ratio: 0.15  

# Logging settings
logging:
  wandb_mode: "offline"
  level: "DEBUG"
  console_level: "ERROR"
  metric_logging_interval: 1
  visualization_interval: 1